### PR TITLE
Adam Roach's review, with a major addition to the doc

### PR DESCRIPTION
**Pull request by paulehoffman**

### CODE REVIEW

**Review by crankycanuck — CHANGES_REQUESTED** [review]
If we're going to add class here, then I think (1) we need to go back to the WG and (2) we need to add something: "In practice, the class for nearly every query is IN.  There are some queries for CH, but they are usually for the purposes of information about the server itself rather than for a different type of address"  I wrote a doc some time ago attempting to deprecate class, because of the way it keeps popping up as though it is viable.

**Comment by paulehoffman** [comment]
I like the additional wording. I'll add it and take the question to the chairs to take to the WG.

**Review by kfujiwara — COMMENTED** [review]
Simple mistake:  "DNS over TLS" should be "DNS over HTTPS" at line 1040. Or "DNS Queries over HTTPS" may be better because it is a draft name.

**Comment by paulehoffman** [comment]
Good catch on "DNS over TLS" -> "DNS over HTTPS". I didn't go with "DNS Queries over HTTPS" because it doesn't really describe the protocol.

**Pull request merged**
